--------------------------------------------------------
--  File created - Wednesday-April-29-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CAT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MARKET"."CAT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CUST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MARKET"."CUST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ITEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MARKET"."ITEM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ORD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MARKET"."ORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PROD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MARKET"."PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "MARKET"."CATEGORIES" 
   (	"CAT_ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "MARKET"."CUSTOMERS" 
   (	"CUST_ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "MARKET"."ORDERS" 
   (	"ORDER_ID" NUMBER, 
	"ORDER_DATE" DATE, 
	"TOTAL" NUMBER, 
	"STATUS" VARCHAR2(50 BYTE), 
	"CUST_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDER_ITEMS
--------------------------------------------------------

  CREATE TABLE "MARKET"."ORDER_ITEMS" 
   (	"ITEM_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"UNIT_PRICE" NUMBER, 
	"ORDER_ID" NUMBER, 
	"PROD_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "MARKET"."PRODUCTS" 
   (	"PROD_ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER, 
	"STOCK" NUMBER, 
	"CAT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MARKET.CATEGORIES
SET DEFINE OFF;
Insert into MARKET.CATEGORIES (CAT_ID,NAME) values (1,'Electronics');
Insert into MARKET.CATEGORIES (CAT_ID,NAME) values (2,'Clothes');
Insert into MARKET.CATEGORIES (CAT_ID,NAME) values (3,'Food');
Insert into MARKET.CATEGORIES (CAT_ID,NAME) values (4,'Books');
Insert into MARKET.CATEGORIES (CAT_ID,NAME) values (5,'Sports');
Insert into MARKET.CATEGORIES (CAT_ID,NAME) values (6,'Furniture');
REM INSERTING into MARKET.CUSTOMERS
SET DEFINE OFF;
Insert into MARKET.CUSTOMERS (CUST_ID,NAME,PHONE,EMAIL,ADDRESS) values (1,'Ahmed Ali','01001234567','ahmed@gmail.com','Cairo');
Insert into MARKET.CUSTOMERS (CUST_ID,NAME,PHONE,EMAIL,ADDRESS) values (2,'Sara Mohamed','01112345678','sara@gmail.com','Alex');
Insert into MARKET.CUSTOMERS (CUST_ID,NAME,PHONE,EMAIL,ADDRESS) values (3,'Mohamed Hassan','01223456789','mohamed@gmail.com','Giza');
Insert into MARKET.CUSTOMERS (CUST_ID,NAME,PHONE,EMAIL,ADDRESS) values (4,'Ali Hassan','01334567890','ali@gmail.com','Cairo');
Insert into MARKET.CUSTOMERS (CUST_ID,NAME,PHONE,EMAIL,ADDRESS) values (5,'Nour Ahmed','01445678901','nour@gmail.com','Alex');
Insert into MARKET.CUSTOMERS (CUST_ID,NAME,PHONE,EMAIL,ADDRESS) values (6,'Omar Khaled','01556789012','omar@gmail.com','Giza');
Insert into MARKET.CUSTOMERS (CUST_ID,NAME,PHONE,EMAIL,ADDRESS) values (7,'Mona Samir','01667890123','mona@gmail.com','Tanta');
Insert into MARKET.CUSTOMERS (CUST_ID,NAME,PHONE,EMAIL,ADDRESS) values (8,'Karim Ali','01098765432','karim@gmail.com','Cairo');
REM INSERTING into MARKET.ORDERS
SET DEFINE OFF;
Insert into MARKET.ORDERS (ORDER_ID,ORDER_DATE,TOTAL,STATUS,CUST_ID) values (1,to_date('29-APR-26','DD-MON-RR'),38000,'Pending',1);
Insert into MARKET.ORDERS (ORDER_ID,ORDER_DATE,TOTAL,STATUS,CUST_ID) values (2,to_date('29-APR-26','DD-MON-RR'),600,'Delivered',2);
Insert into MARKET.ORDERS (ORDER_ID,ORDER_DATE,TOTAL,STATUS,CUST_ID) values (3,to_date('29-APR-26','DD-MON-RR'),13000,'Pending',3);
Insert into MARKET.ORDERS (ORDER_ID,ORDER_DATE,TOTAL,STATUS,CUST_ID) values (4,to_date('29-APR-26','DD-MON-RR'),410,'Delivered',4);
Insert into MARKET.ORDERS (ORDER_ID,ORDER_DATE,TOTAL,STATUS,CUST_ID) values (5,to_date('29-APR-26','DD-MON-RR'),300,'Cancelled',5);
Insert into MARKET.ORDERS (ORDER_ID,ORDER_DATE,TOTAL,STATUS,CUST_ID) values (6,to_date('29-APR-26','DD-MON-RR'),24300,'Pending',6);
Insert into MARKET.ORDERS (ORDER_ID,ORDER_DATE,TOTAL,STATUS,CUST_ID) values (7,to_date('29-APR-26','DD-MON-RR'),5800,'Pending',1);
REM INSERTING into MARKET.ORDER_ITEMS
SET DEFINE OFF;
Insert into MARKET.ORDER_ITEMS (ITEM_ID,QUANTITY,UNIT_PRICE,ORDER_ID,PROD_ID) values (4,2,15000,1,1);
Insert into MARKET.ORDER_ITEMS (ITEM_ID,QUANTITY,UNIT_PRICE,ORDER_ID,PROD_ID) values (5,1,8000,1,2);
Insert into MARKET.ORDER_ITEMS (ITEM_ID,QUANTITY,UNIT_PRICE,ORDER_ID,PROD_ID) values (6,3,200,2,3);
Insert into MARKET.ORDER_ITEMS (ITEM_ID,QUANTITY,UNIT_PRICE,ORDER_ID,PROD_ID) values (7,1,12000,3,5);
Insert into MARKET.ORDER_ITEMS (ITEM_ID,QUANTITY,UNIT_PRICE,ORDER_ID,PROD_ID) values (8,2,500,3,6);
Insert into MARKET.ORDER_ITEMS (ITEM_ID,QUANTITY,UNIT_PRICE,ORDER_ID,PROD_ID) values (9,1,350,4,7);
Insert into MARKET.ORDER_ITEMS (ITEM_ID,QUANTITY,UNIT_PRICE,ORDER_ID,PROD_ID) values (10,3,20,4,8);
Insert into MARKET.ORDER_ITEMS (ITEM_ID,QUANTITY,UNIT_PRICE,ORDER_ID,PROD_ID) values (11,2,150,5,9);
Insert into MARKET.ORDER_ITEMS (ITEM_ID,QUANTITY,UNIT_PRICE,ORDER_ID,PROD_ID) values (12,1,300,6,10);
Insert into MARKET.ORDER_ITEMS (ITEM_ID,QUANTITY,UNIT_PRICE,ORDER_ID,PROD_ID) values (13,2,12000,6,5);
Insert into MARKET.ORDER_ITEMS (ITEM_ID,QUANTITY,UNIT_PRICE,ORDER_ID,PROD_ID) values (14,5,200,7,3);
Insert into MARKET.ORDER_ITEMS (ITEM_ID,QUANTITY,UNIT_PRICE,ORDER_ID,PROD_ID) values (15,3,800,7,11);
Insert into MARKET.ORDER_ITEMS (ITEM_ID,QUANTITY,UNIT_PRICE,ORDER_ID,PROD_ID) values (16,3,800,7,11);
REM INSERTING into MARKET.PRODUCTS
SET DEFINE OFF;
Insert into MARKET.PRODUCTS (PROD_ID,NAME,PRICE,STOCK,CAT_ID) values (1,'Laptop',15000,10,1);
Insert into MARKET.PRODUCTS (PROD_ID,NAME,PRICE,STOCK,CAT_ID) values (2,'Phone',8000,20,1);
Insert into MARKET.PRODUCTS (PROD_ID,NAME,PRICE,STOCK,CAT_ID) values (3,'T-Shirt',200,50,2);
Insert into MARKET.PRODUCTS (PROD_ID,NAME,PRICE,STOCK,CAT_ID) values (4,'Rice 1kg',50,100,3);
Insert into MARKET.PRODUCTS (PROD_ID,NAME,PRICE,STOCK,CAT_ID) values (5,'Tablet',12000,15,1);
Insert into MARKET.PRODUCTS (PROD_ID,NAME,PRICE,STOCK,CAT_ID) values (6,'Headphones',500,30,1);
Insert into MARKET.PRODUCTS (PROD_ID,NAME,PRICE,STOCK,CAT_ID) values (7,'Jeans',350,40,2);
Insert into MARKET.PRODUCTS (PROD_ID,NAME,PRICE,STOCK,CAT_ID) values (8,'Bread',20,200,3);
Insert into MARKET.PRODUCTS (PROD_ID,NAME,PRICE,STOCK,CAT_ID) values (9,'Novel',150,60,4);
Insert into MARKET.PRODUCTS (PROD_ID,NAME,PRICE,STOCK,CAT_ID) values (10,'Football',300,25,5);
Insert into MARKET.PRODUCTS (PROD_ID,NAME,PRICE,STOCK,CAT_ID) values (11,'Chair',800,15,6);
--------------------------------------------------------
--  DDL for Trigger CAT_BI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MARKET"."CAT_BI" 
BEFORE INSERT ON CATEGORIES
FOR EACH ROW
BEGIN
  IF :NEW.CAT_ID IS NULL THEN
    SELECT CAT_SEQ.NEXTVAL INTO :NEW.CAT_ID FROM DUAL;
  END IF;
END;

/
ALTER TRIGGER "MARKET"."CAT_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CUST_BI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MARKET"."CUST_BI" 
BEFORE INSERT ON CUSTOMERS
FOR EACH ROW
BEGIN
  IF :NEW.CUST_ID IS NULL THEN
    SELECT CUST_SEQ.NEXTVAL INTO :NEW.CUST_ID FROM DUAL;
  END IF;
END;

/
ALTER TRIGGER "MARKET"."CUST_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ITEM_BI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MARKET"."ITEM_BI" 
BEFORE INSERT ON ORDER_ITEMS
FOR EACH ROW
BEGIN
  IF :NEW.ITEM_ID IS NULL THEN
    SELECT ITEM_SEQ.NEXTVAL INTO :NEW.ITEM_ID FROM DUAL;
  END IF;
END;

/
ALTER TRIGGER "MARKET"."ITEM_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORD_BI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MARKET"."ORD_BI" 
BEFORE INSERT ON ORDERS
FOR EACH ROW
BEGIN
  IF :NEW.ORDER_ID IS NULL THEN
    SELECT ORD_SEQ.NEXTVAL INTO :NEW.ORDER_ID FROM DUAL;
  END IF;
END;

/
ALTER TRIGGER "MARKET"."ORD_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROD_BI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MARKET"."PROD_BI" 
BEFORE INSERT ON PRODUCTS
FOR EACH ROW
BEGIN
  IF :NEW.PROD_ID IS NULL THEN
    SELECT PROD_SEQ.NEXTVAL INTO :NEW.PROD_ID FROM DUAL;
  END IF;
END;

/
ALTER TRIGGER "MARKET"."PROD_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger UPDATE_ORDER_TOTAL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MARKET"."UPDATE_ORDER_TOTAL" 
AFTER INSERT OR UPDATE OR DELETE ON ORDER_ITEMS
DECLARE
BEGIN
  UPDATE ORDERS O
  SET TOTAL = (
    SELECT NVL(SUM(QUANTITY * UNIT_PRICE), 0)
    FROM ORDER_ITEMS
    WHERE ORDER_ID = O.ORDER_ID
  );
END;

/
ALTER TRIGGER "MARKET"."UPDATE_ORDER_TOTAL" ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "MARKET"."CUSTOMERS" ADD PRIMARY KEY ("CUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "MARKET"."CATEGORIES" ADD PRIMARY KEY ("CAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "MARKET"."ORDER_ITEMS" ADD PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "MARKET"."PRODUCTS" ADD PRIMARY KEY ("PROD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "MARKET"."ORDERS" ADD PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "MARKET"."ORDERS" ADD CONSTRAINT "FK_ORDERS_CUSTOMER" FOREIGN KEY ("CUST_ID")
	  REFERENCES "MARKET"."CUSTOMERS" ("CUST_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "MARKET"."ORDER_ITEMS" ADD CONSTRAINT "FK_ITEMS_ORDER" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "MARKET"."ORDERS" ("ORDER_ID") ENABLE;
  ALTER TABLE "MARKET"."ORDER_ITEMS" ADD CONSTRAINT "FK_ITEMS_PRODUCT" FOREIGN KEY ("PROD_ID")
	  REFERENCES "MARKET"."PRODUCTS" ("PROD_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "MARKET"."PRODUCTS" ADD CONSTRAINT "FK_PRODUCTS_CAT" FOREIGN KEY ("CAT_ID")
	  REFERENCES "MARKET"."CATEGORIES" ("CAT_ID") ENABLE;
